title: Streakeeper
description: >
  Streakeeper helps keep your Duolingo streak by automatically
  buying a Freeze every day, even if you forget or can't access
  the internet that day.

theme: jekyll-theme-minimal
google_analytics: UA-40708916-4
